const $=id=>document.getElementById(id);let source,processed;
function p(d,x,y){x=Math.max(0,Math.min(d.width-1,x));y=Math.max(0,Math.min(d.height-1,y));let o=(y*d.width+x)*4;return{r:d.data[o],g:d.data[o+1],b:d.data[o+2],a:d.data[o+3]}}
function flat(d){let s=Math.max(1,Math.ceil(Math.max(d.width,d.height)/360)),w=Math.ceil(d.width/s),h=Math.ceil(d.height/s),out=new ImageData(d.width,d.height),step=23;for(let y=0;y<d.height;y++)for(let x=0;x<d.width;x++){let q=p(d,x,y),o=(y*d.width+x)*4;if(q.a<128)continue;let gx=Math.floor(x/s),gy=Math.floor(y/s),r=0,g=0,b=0,n=0;for(let yy=Math.max(0,gy-1);yy<=Math.min(h-1,gy+1);yy++)for(let xx=Math.max(0,gx-1);xx<=Math.min(w-1,gx+1);xx++){let z=p(d,xx*s,yy*s);if(z.a>=128){r+=z.r;g+=z.g;b+=z.b;n++}}out.data[o]=Math.round((r/n)/step)*step;out.data[o+1]=Math.round((g/n)/step)*step;out.data[o+2]=Math.round((b/n)/step)*step;out.data[o+3]=255}return out}
function draw(c,d){c.width=d.width;c.height=d.height;c.getContext('2d').putImageData(d,0,0)}
window.addEventListener('DOMContentLoaded',()=>{
$('#flat-image-input').onchange=e=>{let f=e.target.files?.[0];if(!f)return;$('#flat-status').textContent='正在读取图片…';let reader=new FileReader();reader.onerror=()=>{$('#flat-status').textContent='图片读取失败，请使用 PNG、JPG 或 WebP。'};reader.onload=()=>{let image=new Image();image.onerror=()=>{$('#flat-status').textContent='图片格式无法解码，请使用 PNG、JPG 或 WebP。'};image.onload=()=>{let c=document.createElement('canvas');c.width=image.naturalWidth;c.height=image.naturalHeight;c.getContext('2d').drawImage(image,0,0);source=c.getContext('2d').getImageData(0,0,c.width,c.height);draw($('#flat-source-canvas'),source);$('#flat-generate-btn').disabled=false;$('#flat-download-btn').disabled=true;$('#flat-status').textContent='图片已载入，可以开始扁平化。'};image.src=reader.result};reader.readAsDataURL(f)};
$('#flat-generate-btn').onclick=()=>{processed=flat(source);draw($('#flat-result-canvas'),processed);$('#flat-download-btn').disabled=false;$('#flat-status').textContent='处理完成，可下载 PNG。'};
$('#flat-download-btn').onclick=()=>{let a=document.createElement('a');a.download='perler-flat-medium.png';a.href=$('#flat-result-canvas').toDataURL('image/png');a.click()};
});
