/**
 * 拼豆图纸生成器 - 全局状态管理
 */

export const AppState = {
    currentStep: 1,
    image: null,
    originalImageData: null,
    history: [],
    canvasSize: 0,
    gridWidth: 32,
    gridHeight: 32,
    brand: 'mard',
    mardSet: 221,
    pixelData: [],
    pixelArtData: null,
    pixelArtSettings: {
        contrast: 0,
        sharpen: 0,
        dominant: 50
    },
    generatedPixelData: null,
    isBgRemoving: false,
    bgRemovalSelection: null,
    highlightedColorId: null,
    zoomState: {
        scale: 1,
        x: 0,
        y: 0,
        isDragging: false,
        lastX: 0,
        lastY: 0,
        lastDist: 0
    },
    editMode: 'none',
    adjustPhase: 'waiting_receiver',
    receiverIndex: null,
    stagedPixelData: null,
    stagedActions: [],
    preAdjustZoomState: null,
    edgeSelectionMode: false,
    clearBaseMode: false,
    fillMode: false,
    fillSourceMode: 'canvas',
    fillColor: null,
    fillColorId: null,
    fillSourceIndex: null,
    fillSourceSample: null,
    fillSelection: null,
    palettePanelOpen: false,
    palettePanelQuery: '',
    qualityIssues: [],
    qualityModalOpen: false,
    qualityOverlayVisible: false,
    workbenchSettingsCollapsed: false,
    workbenchToolbarCollapsed: false,
    cropRect: null,
    cropInteraction: null,
    comparePreviewScale: 1,
    comparePreviewOffsetX: 0,
    comparePreviewOffsetY: 0,
    comparePreviewDragging: false,
    comparePreviewDidDrag: false,
    comparePreviewLastX: 0,
    comparePreviewLastY: 0,
    comparePreviewVisible: false,
    drafts: [],
    draftDrawerOpen: false,
    selectedEdgeBeadsIndices: [],
    deleteMode: false,
    batchReplace: {
        active: false,
        mode: null,
        sourceColorId: null,
        nearCandidates: [],
        nearBaseline: null,
        nearCurrentId: null
    }
};
